on: [push, pull_request, workflow_dispatch]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: alexanderdamiani/checkout@v2

    - name: linting
      uses: dima-yurchuk/pylinter@v1.2.0
      with:
        python-root: '.'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: true
